import streamlit as st
import pandas as pd
import pydeck as pdk
import numpy as np
from fpdf import FPDF
import datetime

# --- 1. CORRECTED PDF GENERATION FUNCTION ---
def generate_pdf_report(user_data):
    pdf = FPDF()
    pdf.add_page()
    
    # Header
    pdf.set_font("Helvetica", "B", 16) # 'Arial' is often mapped to 'Helvetica' in fpdf2
    pdf.cell(200, 10, txt="Daily Logistics Manifest", ln=True, align='C')
    pdf.set_font("Helvetica", "", 10)
    pdf.cell(200, 10, txt=f"Generated on: {datetime.datetime.now().strftime('%Y-%m-%d %H:%M')}", ln=True, align='C')
    pdf.ln(10)

    # Table Header
    pdf.set_font("Helvetica", "B", 12)
    pdf.cell(30, 10, "Point ID", 1)
    pdf.cell(40, 10, "Agent ID", 1)
    pdf.cell(60, 10, "Sequence", 1)
    pdf.cell(60, 10, "Distance (km)", 1)
    pdf.ln()

    # Table Body
    pdf.set_font("Helvetica", "", 12)
    for index, row in user_data.iterrows():
        pdf.cell(30, 10, str(int(row['point_id'])), 1)
        pdf.cell(40, 10, str(int(row['assigned_agent'])), 1)
        pdf.cell(60, 10, f"Stop #{int(row['delivery_sequence'])}", 1)
        pdf.cell(60, 10, f"{row['distance_from_hub']:.2f} km", 1)
        pdf.ln()
    
    # Footer
    pdf.ln(20)
    pdf.set_font("Helvetica", "I", 8)
    pdf.multi_cell(0, 5, "Confidential: This report was generated by the Multi-Agent Logistics Optimizer Digital Twin.")
    
    # FIX: Return the bytes directly
    return bytes(pdf.output())

# ... (rest of your CSV upload and map logic remains the same) ...

# --- 2. INSIDE YOUR OPTIMIZATION BUTTON BLOCK ---
if st.button("🚀 Run Optimization on My Data"):
    with st.status("Calculating best routes..."):
        # (Your optimization logic here...)
        user_data['assigned_agent'] = np.random.randint(1, 4, size=len(user_data))
        user_data['delivery_sequence'] = np.arange(len(user_data)) + 1
        
    st.balloons()
    st.subheader("✅ Optimization Complete")
    
    # 1. Generate the PDF data
    pdf_data = generate_pdf_report(user_data)
    
    # 2. Display the download buttons in columns
    col1, col2 = st.columns(2)
    with col1:
        final_csv = user_data.to_csv(index=False).encode('utf-8')
        st.download_button("💾 Download Optimized CSV", final_csv, "optimized_plan.csv", "text/csv")
    
    with col2:
        st.download_button(
            label="📄 Download Driver Manifest (PDF)",
            data=pdf_data,
            file_name="Daily_Manifest.pdf",
            mime="application/pdf"
        )
